backport drm from drm-next 86e81f0
Sync to commit:

commit 86e81f0e624b55fa9f1560c3b64bc80e458c5168
Author:     David Herrmann <dh.herrmann@gmail.com>
AuthorDate: Thu Jul 25 18:02:31 2013 +0200
Commit:     Dave Airlie <airlied@redhat.com>
CommitDate: Thu Aug 1 10:28:09 2013 +1000

    drm/mm: include required headers in drm_mm.h

    We need BUG_ON(), spinlock_t and standard kernel data-types so include the
    right headers.

    Subject: [drm-intel:drm-intel-nightly 154/166] include/drm/drm_mm.h:67:2:
     error: unknown type name 'spinlock_t'
    Message-ID: <51f14693.g5HGdcuw2v3m8FOd%fengguang.wu@intel.com>

    In case it didn't link to it correctly. Somehow this bug doesn't occur
    here on my machine, hmm. But I think fixing drm_mm.h is better than
    changing the include-order in drm_vma_manager.h, so this is what I
    did.

    Signed-off-by: David Herrmann <dh.herrmann@gmail.com>
    Signed-off-by: Dave Airlie <airlied@redhat.com>

Signed-off-by: Rob Clark <robdclark@gmail.com>